name:                odlang
version:             0.1.0.0
github:              "githubuser/odlang"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/odlang#readme>

dependencies:
- base >= 4.7 && < 5
- bifunctors >= 5.6 && < 6
- deriving-compat >= 0.6 && < 1
- mtl >= 2.3 && < 3
- containers >= 0.8 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  odlang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - odlang

tests:
  odlang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - odlang

default-extensions:
- PatternSynonyms
- TypeApplications
- StandaloneDeriving
- GADTs
- QuantifiedConstraints
- UndecidableInstances
- DeriveFunctor
- DeriveTraversable
- ScopedTypeVariables
- BlockArguments
- LambdaCase
- ImportQualifiedPost
- ViewPatterns
- FlexibleContexts
